# this is a dev properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
wechat:
  appId: 
  secret: 
  token: robot
  app:
    appId: 
    secret: 